### PR TITLE
LRCI-1398 Allow relevant test properties to be specific to sub-modules of an app

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1398

From https://github.com/michaelhashimoto/liferay-portal/pull/2365

Please feel free to forward this pull after testing.  Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Tested [here.](https://github.com/brittneyq/liferay-portal/pull/170). Will be forwarding now.

**Pull request closed without merging**
