### PR TITLE
LPD-40027 SF

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @brittneyq I am working on a SF rule for `test.properties`, I think I need to fix something before the new SF rule to be done, please see the last commit.
Thanks.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by brittneyq** [comment]
Hi @ling-alan-huang , the change looks good to me! Good catch!

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
